name: OCN-Scrim
main: me.parapenguin.overcast.scrimmage.Scrimmage
version: 0.2.6
author: [ParaPenguin]
website: http://teamloading.com/
load: STARTUP
commands:
  join:
    description: Join Command.
  setteam:
    aliases: [st]
    description: Join Command.