name: OCN-Scrim
main: me.parapenguin.overcast.scrimmage.Scrimmage
version: 0.2.6
author: [ParaPenguin]
website: http://teamloading.com/
load: STARTUP
commands:
  join:
    description: Join the match.
  setteam:
    aliases: [st]
    description: Set the name of a team.
  setnext:
    aliases: [sn]
    description: Set the next map.
  global:
    aliases: [g]
    description: Global chat.
  end:
    aliases: [cancel]
    description: Stop/End the game.
  start:
    description: Start the starting timer.
  cycle:
    description: Cycle to the next map.
